apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: busyloop
  name: busyloop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: busyloop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: busyloop
    spec:
      nodeSelector:
        node-role.kubernetes.io/node: "true"
      containers:
      - image: quay.io/gravitational/busyloop:latest
        imagePullPolicy: Always
        name: busyloop
      terminationGracePeriodSeconds: 30
